### ISSUE TITLE
 DatasetInfo.__init__() got an unexpected keyword argument 'task_templates'

### ISSUE THREAD

**Issue by nikilpatel94** [project-miracl/nomiracl#2]
Looks like this is originating from from [https://huggingface.co/datasets/miracl/nomiracl/blob/5911804e87c5d80decbff059bb98732ab3b5dd16/nomiracl.py#L144](here)

**Comment by DhananjayAshok** [comment]
Getting the same issue

**Comment by thakur-nandan** [comment]
Apologies, this issue was caused by a breaking change in the huggingface `datasets.DatasetInfo` class in the latest version.
The error has been resolved now!

Thanks for letting me know @nikilpatel94 @DhananjayAshok!

```python
## Load the nomiracl dataset

import datasets

language = 'german'  # or any of the 18 languages
subset = 'relevant'  # or 'non_relevant'
split = 'test'       # or 'dev' for development split

# four combinations available: 'dev.relevant', 'dev.non_relevant', 'test.relevant' and 'test.non_relevant'
nomiracl = datasets.load_dataset('miracl/nomiracl', language, split=f'{split}.{subset}', trust_remote_code=True)
```

Regards,
Nandan
